import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { Script, createContext, runInContext } from 'node:vm';

const root = new URL('../', import.meta.url);
const read = path => readFile(new URL(path, root), 'utf8');
const contentFiles = [
  ...[1, 2, 3, 4].map(number => `src/curriculum/module-${number}.js`),
  'src/curriculum/final-exam.js',
  'src/course.js',
];
const content = (await Promise.all(contentFiles.map(read))).join('\n');
runInContext(content + '\nvalidateCurriculum(COURSE_MODULES, FINAL_EXAM_QUESTIONS);', createContext({}), { timeout: 1000 });

const code = [content, await read('src/activities.js'), await read('src/app.js')].join('\n');
const script = `'use strict';\n(() => {\n${code}\n})();`;
new Script(script, { filename: 'digital-safety-wellness.html' });
if (/<\/script/i.test(script)) throw new Error('Source must not contain a closing script tag.');
const shell = await read('src/shell.html');
for (const marker of ['<!-- COURSE_STYLE -->', '<!-- COURSE_SCRIPT -->']) {
  if (shell.split(marker).length !== 2) throw new Error(`Expected exactly one ${marker}`);
}
// Replacements use functions so authored dollar signs remain literal.
const styles = await read('src/styles.css');
const html = '<!-- Generated by node scripts/build.mjs. Edit src/ instead. -->\n'
  + shell.replace('<!-- COURSE_STYLE -->', () => `<style>\n${styles}</style>`)
    .replace('<!-- COURSE_SCRIPT -->', () => `<script>\n${script}\n</script>`);
const target = new URL('digital-safety-wellness.html', root);
if (process.argv.includes('--check')) {
  if (await readFile(target, 'utf8') !== html) {
    throw new Error('Download is out of date. Run node scripts/build.mjs and commit the generated HTML.');
  }
  console.log('Curriculum valid; generated download is current.');
} else {
  await writeFile(target, html);
  console.log(`Built ${fileURLToPath(target)} (${Buffer.byteLength(html).toLocaleString()} bytes).`);
}
